{
 "title": "JVM Overview (OpenTelemetry)",
 "description": "Dashboard for JVM metrics with OpenTelemetry instrumentation",
 "tags": [
  "JVM",
  "open-telemetry",
  "Java",
  "otel",
  "opentelemetry",
  "otlp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(process_runtime_jvm_memory_usage{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "description": "CPU utilization for the whole system",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_utilization{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Utilization",
   "type": "timeseries",
   "description": "How much of the available heap memory is used",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (process_runtime_jvm_memory_usage{job=~\"$job\",type=\"heap\", instance=~\"$instance\"}) / on(instance) sum by (instance) (process_runtime_jvm_memory_limit{job=~\"$job\",type=\"heap\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - used"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "timeseries",
   "description": "Percentage of time spend for garbage collection pauses",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(process_runtime_jvm_gc_duration_sum{job=~\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "timeseries",
   "description": "Number of currently loaded classes",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_runtime_jvm_classes_current_loaded{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of currently executing (also called \"live\") threads",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_threads_count{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}