changelog:
  categories:
    - title: Upstream Updates
      labels:
        - update-upstream
    - title: 🏕 Features
      labels:
        - "*"
      exclude:
        labels:
          - chore
          - dependencies
          - update-upstream
    - title: 🧹 Chore
      labels:
        - chore
    - title: 👒 Dependencies
      labels:
        - dependencies
