/*
 * Copyright Grafana Labs
 * SPDX-License-Identifier: Apache-2.0
 */

package com.grafana.extensions.resources.internal;

// This class is generated by custom/build.gradle.  Do not edit.

public class DistributionVersion {

  public static final String VERSION = "10.0.0-SNAPSHOT";
}
