name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions: {}

jobs:
  release:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    concurrency:
      group: "${{ github.workflow }}-${{ github.sha }}"
      cancel-in-progress: false

    permissions:
      actions: read
      attestations: write
      contents: write
      id-token: write

    steps:
      - name: Check out
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: v2026.4.19
          sha256: 6b58ff5f1e1ce98ed2b7e5372c344ea48182c460e5b6df12d9e0def35aad4438
          cache: false

      - name: Build
        run: mise run build-release
        env:
          TAG: ${{ github.ref_name }}

      - name: Attest artifacts
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: |
            agent/build/libs/grafana-opentelemetry-java.jar

      - name: Get release actor user type
        id: get-release-actor-user-type
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $actorType = (gh api "repos/${env:GITHUB_REPOSITORY}/actions/workflows/publish-release.yml/runs" --jq '.workflow_runs[0].actor.type')
          "release-actor-user-type=${actorType}" >> ${env:GITHUB_OUTPUT}

      - name: Release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_IS_DRAFT: ${{ steps.get-release-actor-user-type.outputs.release-actor-user-type != 'Bot' }}
        run: |
          gh release create "${GITHUB_REF_NAME}" "agent/build/libs/grafana-opentelemetry-java.jar" "LICENSE" "--draft=${RELEASE_IS_DRAFT}" --generate-notes --repo "${GITHUB_REPOSITORY}"

      - name: Push to Docker (for OpenTelemetry Operator)
        uses: grafana/shared-workflows/actions/docker-build-push-image@b3d136565946d8788dd6812881fb0fb2fe14bacb # docker-build-push-image/v0.2.0
        with:
          context: .
          gar-environment: "prod"
          gar-image: grafana-opentelemetry-java
          gar-registry: "us-docker.pkg.dev"
          file: scripts/otel_operator/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          registries: gar
          tags: |
            type=match,pattern=v(.*),group=1
            latest
