name: Renovate
on:
  schedule:
    - cron: "16 */4 * * *"
  workflow_dispatch:

jobs:
  renovate:
    permissions:
      contents: read # needed to read the contents of the repository
      id-token: write # needed to create a GitHub App token
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: retrieve secrets
        id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@7d18a46aafb8b875ed76a0bc98852d74b91e7f91 # v1.0.0
        with:
          common_secrets: |
            GRAFANA_RENOVATE_APP_ID=grafana-renovate-app:app-id
            GRAFANA_RENOVATE_PRIVATE_KEY=grafana-renovate-app:private-key

      - name: create GitHub app token
        id: app-token
        # Beware that the token generated here has elevated permissions wrt to
        # the ones set in the action. In particular, it will be able to write
        # to the repository (e.g. create branches) and create pull requests.
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ env.GRAFANA_RENOVATE_APP_ID }}
          private-key: ${{ env.GRAFANA_RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@67a664fc9b4481b33a3eff6ee9edfb7a7b9dfa1e # v41.0.2
        with:
          renovate-version: 39.12.0@sha256:37991e23a3fa394e5b22cf448351c99efc69040c266da711055bd6146e962381
          token: "${{ steps.app-token.outputs.token }}"
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: GrafanaRenovateBot
